name: Deploy
on:
  push:
    tags:
      - '*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      # Prevents other hosts from stopping if one host fails
      fail-fast: false
      matrix:
        # save SSH_HOSTS_JSON as json array (eg. ["host1.host", "host2.host"])
        host: ${{ fromJson(vars.SSH_HOSTS_JSON) }}

    steps:
      - name: Reload Go Libraries on ${{ matrix.host }}
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ matrix.host }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            echo "Connected to target host: ${{ matrix.host }}"
            /usr/local/bin/build-go-mods
